defmodule Weheat.DTO.EnergyViewDto do
  @moduledoc "Mirrors `EnergyViewDto` from the Python weheat SDK. Generated by tools/gen_dto.py, do not edit."

  use Weheat.DTO,
    fields: [
      interval: {"interval", :string},
      time_bucket: {"timeBucket", :datetime},
      total_ein_heating: {"totalEInHeating", :float},
      total_ein_standby: {"totalEInStandby", :float},
      total_ein_dhw: {"totalEInDhw", :float},
      total_ein_heating_defrost: {"totalEInHeatingDefrost", :float},
      total_ein_dhw_defrost: {"totalEInDhwDefrost", :float},
      total_ein_cooling: {"totalEInCooling", :float},
      total_e_out_heating: {"totalEOutHeating", :float},
      total_e_out_dhw: {"totalEOutDhw", :float},
      total_e_out_heating_defrost: {"totalEOutHeatingDefrost", :float},
      total_e_out_dhw_defrost: {"totalEOutDhwDefrost", :float},
      total_e_out_cooling: {"totalEOutCooling", :float},
      average_power_ein_heating: {"averagePowerEInHeating", :float},
      average_power_ein_standby: {"averagePowerEInStandby", :float},
      average_power_ein_dhw: {"averagePowerEInDhw", :float},
      average_power_ein_heating_defrost: {"averagePowerEInHeatingDefrost", :float},
      average_power_ein_dhw_defrost: {"averagePowerEInDhwDefrost", :float},
      average_power_ein_cooling: {"averagePowerEInCooling", :float},
      average_power_e_out_heating: {"averagePowerEOutHeating", :float},
      average_power_e_out_dhw: {"averagePowerEOutDhw", :float},
      average_power_e_out_heating_defrost: {"averagePowerEOutHeatingDefrost", :float},
      average_power_e_out_dhw_defrost: {"averagePowerEOutDhwDefrost", :float},
      average_power_e_out_cooling: {"averagePowerEOutCooling", :float}
    ]
end
