defmodule Weheat.DTO.PaginationMetadata do
  @moduledoc "Mirrors `PaginationMetadata` from the Python weheat SDK. Generated by tools/gen_dto.py, do not edit."

  use Weheat.DTO,
    fields: [
      total_count: {"totalCount", :integer},
      page_size: {"pageSize", :integer},
      current_page: {"currentPage", :integer},
      total_pages: {"totalPages", :integer}
    ]
end
