defmodule Weheat.DTO.ReadHeatPumpDto do
  @moduledoc "Mirrors `ReadHeatPumpDto` from the Python weheat SDK. Generated by tools/gen_dto.py, do not edit."

  use Weheat.DTO,
    fields: [
      control_board_id: {"controlBoardId", :string},
      name: {"name", :string},
      model: {"model", :integer},
      dhw_type: {"dhwType", :integer},
      boiler_type: {"boilerType", :integer},
      status: {"status", :integer},
      commissioned_at: {"commissionedAt", :datetime},
      serial_number: {"serialNumber", :string},
      part_number: {"partNumber", :string},
      state: {"state", :integer},
      id: {"id", :string}
    ]
end
