defmodule Weheat.DTO.ReadAllHeatPumpDtoPagedResponse do
  @moduledoc "Mirrors `ReadAllHeatPumpDtoPagedResponse` from the Python weheat SDK. Generated by tools/gen_dto.py, do not edit."

  use Weheat.DTO,
    fields: [
      metadata: {"metadata", Weheat.DTO.PaginationMetadata},
      data: {"data", {:list, Weheat.DTO.ReadAllHeatPumpDto}}
    ]
end
