defmodule Weheat.DTO.ReadUserDto do
  @moduledoc "Mirrors `ReadUserDto` from the Python weheat SDK. Generated by tools/gen_dto.py, do not edit."

  use Weheat.DTO,
    fields: [
      id: {"id", :string},
      first_name: {"firstName", :string},
      last_name: {"lastName", :string},
      role: {"role", :integer},
      email: {"email", :string},
      updated_on: {"updatedOn", :datetime},
      created_on: {"createdOn", :datetime}
    ]
end
