defmodule Weheat.DTO.TotalEnergyAggregate do
  @moduledoc "Mirrors `TotalEnergyAggregate` from the Python weheat SDK. Generated by tools/gen_dto.py, do not edit."

  use Weheat.DTO,
    fields: [
      heat_pump_id: {"heatPumpId", :string},
      total_ein_heating: {"totalEInHeating", :float},
      total_ein_standby: {"totalEInStandby", :float},
      total_ein_dhw: {"totalEInDhw", :float},
      total_ein_heating_defrost: {"totalEInHeatingDefrost", :float},
      total_ein_dhw_defrost: {"totalEInDhwDefrost", :float},
      total_ein_cooling: {"totalEInCooling", :float},
      total_e_out_heating: {"totalEOutHeating", :float},
      total_e_out_dhw: {"totalEOutDhw", :float},
      total_e_out_heating_defrost: {"totalEOutHeatingDefrost", :float},
      total_e_out_dhw_defrost: {"totalEOutDhwDefrost", :float},
      total_e_out_cooling: {"totalEOutCooling", :float},
      total_ein_iu_standby: {"totalEInIUStandby", :float},
      total_ein_iu_heating: {"totalEInIUHeating", :float},
      total_ein_iu_dhw: {"totalEInIUDhw", :float},
      total_ein_iu_heating_defrost: {"totalEInIUHeatingDefrost", :float},
      total_ein_iu_dhw_defrost: {"totalEInIUDhwDefrost", :float},
      total_ein_iu_cooling: {"totalEInIUCooling", :float}
    ]
end
